import {escapeHtml as esc,stateLabel,productLabel,taskNames,clock,minutes} from './format.mjs';
import {analyzeRun,durationStatuses,durationTenths} from './replay-model.mjs';
import {renderRunConditions} from './run-conditions.mjs';
import {renderCustomerResults,renderCustomerComparison} from './customer-results.mjs';
import {analyzeLineBuffers} from './buffer-analysis.mjs';

export const metric=(label,value,unit='',sub='',tone='',icon='')=>`<div class="metric ${tone}"><div class="metric-label">${esc(label)}<span class="metric-icon" aria-hidden="true">${icon}</span></div><strong>${esc(value)}</strong><small>${esc(unit)}</small>${sub?`<span class="metric-sub">${esc(sub)}</span>`:''}</div>`;
const utilBars=data=>data.agfs.map(a=>`<div class="util-row"><span>${esc(a.id)}</span><div class="util-track"><i style="width:${a.utilizationPct}%"></i></div><b>${a.utilizationPct.toFixed(1)}%</b></div>`).join('');
const kindTable=data=>`<div class="table-scroll"><table><thead><tr><th>搬送区分</th><th>要求</th><th>完了</th><th>未完了</th></tr></thead><tbody>${data.byKind.map(k=>`<tr><td><span class="mono">${k.kind}</span> ${taskNames[k.kind]}</td><td>${k.requested}</td><td>${k.completed}</td><td>${k.pending}</td></tr>`).join('')}</tbody></table></div>`;
function renderAnalysisMetrics(run,data=analyzeRun(run)) {
  const graph=run.scenario.motionModel==='synthetic_graph',label=s=>stateLabel(s,graph);
  const graphStatuses=['turning','positioning_for_pickup','picking_fork_inserted','positioning_for_dropoff','dropping_fork_inserted','waiting_motion_configuration','waiting_avoidance','waiting_interference','waiting_wrapper_input','waiting_charge_place'];
  const categories=durationStatuses.filter(s=>(graph||!s.startsWith('handling_')&&!graphStatuses.includes(s))&&(run.scenario.postTaskPolicy||!['moving_to_wait','hp_wait','waiting_hp_instruction','waiting_hp_capacity','waiting_hp_route'].includes(s)));
  return `<div class="analysis-metrics">${metric('搬送要求数',data.requested,'件','01〜05の発行済み要求','accent','↗')}${metric('完了タスク',data.completed,'件','実行期間内の完了','success','✓')}${metric('保留タスク',data.held,'件',`未完了 ${data.pending}件 / 02発行前保留 ${data.preRequestHeld}PL`,'warning','◷')}${metric('AGF平均稼働率',data.utilizationPct.toFixed(1),'%','空走・積載・旋回・荷役','accent','▥')}
    ${graph?metric('停止旋回',minutes(data.turningMs),'分','4台合計・並進移動なし')+metric('荷役姿勢への移行',minutes(data.positioningMs),'分','荷受け／荷下ろしの姿勢移行')+metric('フォーク挿入後の荷役',minutes(data.forkHandlingMs),'分','姿勢移行時間と別集計')+metric('走行・荷役設定待ち',minutes(data.motionConfigurationWaitMs),'分','未確定値を補完せず保留'):''}
    ${metric('待機時間',minutes(data.idleMs),'分','4台合計・倉庫待機を含む')}${metric('交通待ち',minutes(data.trafficWaitMs),'分','区間・交差点・シャッター')}${metric('荷受け許可待ち',minutes(data.pickupWaitMs??0),'分','荷受け前の設備許可待ち')}${metric('充電時間',minutes(data.chargeMs),'分','4台合計・充電中')}${metric('充電待ち時間',minutes(data.chargeWaitMs),'分','4台合計・2口の空き待ち')}${run.scenario.postTaskPolicy?metric('倉庫復帰走行',minutes(data.waitReturnMs),'分','通常空走とは別集計')+metric('うち倉庫待機',minutes(data.hpWaitMs),'分','4か所の待機場所への到着後')+metric('倉庫復帰保留',minutes(data.hpBlockedMs),'分','復帰先の使用待ちなど'):''}</div>
    <section class="panel"><div class="panel-heading"><div><h2>AGF タイムライン</h2><span class="muted">保存済みスナップショットの状態継続時間 · ${run.scenario.durationMin}分間</span></div><span class="badge">全期間</span></div><div class="timeline-axis">${[0,.25,.5,.75,1].map(n=>`<span>${clock(data.durationMs*n)}</span>`).join('')}</div>
    ${data.agfs.map(a=>`<div class="timeline-row"><strong>${esc(a.id)}</strong><div class="timeline-track" role="img" aria-label="${a.id} 稼働率${a.utilizationPct.toFixed(1)}%、状態別時間は下表参照">${a.timeline.map(s=>`<span class="timeline-segment timeline-${esc(s.status)}" style="width:${(s.endMs-s.startMs)*100/data.durationMs}%" title="${esc((label(s.status))+' '+clock(s.startMs)+'–'+clock(s.endMs)+(s.taskId?' '+s.taskId:''))}"></span>`).join('')}</div></div>`).join('')}
    <div class="timeline-legend">${categories.map(s=>`<span><i class="legend-dot timeline-${s}"></i>${label(s)}</span>`).join('')}</div></section>
    <div class="analysis-grid"><section class="panel"><div class="panel-heading"><h2>搬送別実績</h2><span class="muted">件</span></div>${kindTable(data)}</section><section class="panel"><div class="panel-heading"><h2>AGF別 稼働率</h2><span class="muted">全期間に対する作業時間</span></div>${utilBars(data)}<p class="method-note">稼働率＝空走＋積載走行＋停止旋回＋荷受け＋荷下ろし（姿勢移行・フォーク挿入後を各1回計上）。交通待ち・設定待ち・荷受け許可待ち・充電・充電移動・倉庫復帰・荷下ろし待ちは含めません。旋回の電池消費対象はRun条件で別管理します。固定時間モデルでは走行と荷役を合算します。</p></section></div>
    ${data.storage?`<section class="panel section"><div class="panel-heading"><h2>倉庫容量と入庫実績</h2><span class="badge">理論最大 ${data.storage.theoretical} PL</span></div><div class="analysis-metrics">${metric('割当済み行容量',data.storage.assignedCapacity,'PL','系列／特注に割当済み')+metric('未割当行容量',data.storage.unassignedCapacity,'PL','入庫候補外')+metric('使用中',data.storage.occupied,'PL')+metric('予約済み',data.storage.reserved,'PL')+metric('端数による上段不可',data.storage.blockedUpper,'位置')+metric('今すぐ下段条件を満たす空き',data.storage.immediatelyPlaceable,'位置')+metric('追加可能上限',data.storage.additionalIfFull,'PL','今後すべて満載の仮定')+metric('追加可能数',data.storage.additionalIfPartial,'PL','今後すべて端数の仮定')}</div><p class="method-note">割当済み行・現在の在庫／予約／許可による構造上の数です。空き下段の将来の満載／端数で上段の可否が変わります。予約だけの下段は配置済みとは扱いません。行占有・経路・許可の判定は各タスクで別途行います。</p><div class="table-scroll"><table><thead><tr><th>系列／銘柄／積載状態</th><th>対象PL</th><th>入庫</th><th>未入庫</th></tr></thead><tbody>${data.products.map(p=>`<tr><td>${esc(productLabel(p))}</td><td>${p.requested}</td><td>${p.stored}</td><td>${p.pending}</td></tr>`).join('')}</tbody></table></div></section>`:''}
    <section class="panel"><div class="panel-heading"><h2>AGF別 時間内訳</h2><span class="muted">単位：分 / 各行の合計は実行時間（端数調整）</span></div><div class="table-scroll"><table><thead><tr><th>AGF</th>${categories.map(s=>`<th>${label(s)}</th>`).join('')}</tr></thead><tbody>${data.agfs.map(a=>`<tr><td>${a.id}</td>${categories.map(s=>`<td title="${a.durations[s]??0} ms">${(durationTenths(a.durations)[s]/10).toFixed(1)}</td>`).join('')}</tr>`).join('')}</tbody></table></div></section>
    <p class="method-note section">集計根拠：実行開始から終了まで、同時刻イベントは順序適用後の状態を使用。末尾イベント後の継続時間も含みます。内訳表は0.1分単位で合計が一致するよう最大剰余法で端数を配分します。稼働率は丸め前のミリ秒値で算出します。合成グラフの交通待ちはイベント状態から集計します。実CAD距離・確定ETA・現場性能ではありません。</p>`;
}
export function renderBufferAnalysis(run,data=analyzeLineBuffers(run)){
  const reasonLabel={LINE_BUFFER_FULL:'系列バッファ空き待ち',EMPTY_PALLET:'空パレット待ち',
    RECOVERY_POLICY_UNSET:'再開方式の設定待ち',WAIT_NEXT_TAKT:'補充済み・次タクト待ち'};
  return `<section class="panel section buffer-analysis"><div class="panel-heading"><h2>系列バッファ分析</h2><span class="muted">保存済み搬送履歴から集計</span></div>
    <div class="analysis-metrics">${metric('バッファ満杯発生回数',data.fullCount,'回','','warning')}
    ${metric('バッファ満杯停止時間',minutes(data.stopMs),'分','全系列の停止時間の合計')}
    ${metric('最大連続停止時間',minutes(data.maxStopMs),'分','1系列・1回の停止の最大')}
    ${metric('生産遅延PL数',data.delayedPalletCount,'PL','バッファ満杯で生成を保留したPL')}
    ${metric('終了時生産停止系列数',data.endedStoppedLineCount,'系列',`うちバッファ待ち起因 ${data.endedBufferStoppedLineCount}系列`,'warning')}</div>
    <div class="table-scroll"><table><thead><tr><th>系列</th><th>容量</th><th>最大在荷</th><th>満杯発生回数</th><th>停止時間</th><th>最大停止時間</th><th>遅延PL</th><th>終了時状態</th></tr></thead>
    <tbody>${data.lines.map(line=>`<tr data-buffer-line="${esc(line.lineId)}"><td>${esc(line.lineId)}（系列${esc(line.lineId.slice(1))}）</td><td>${line.capacity} PL</td><td>${line.maxQuantity} PL</td><td>${line.fullCount}回</td><td>${minutes(line.stopMs)}分</td><td>${minutes(line.maxStopMs)}分</td><td>${line.delayedPalletCount} PL</td><td>${esc(line.endedStatus)}${line.endedReason?`<br><span class="muted">${esc(reasonLabel[line.endedReason]??'生産条件待ち')}</span>`:''}</td></tr>`).join('')}</tbody></table></div>
    <p class="method-note">停止時間は、搬送履歴の「系列バッファ満杯・生産停止」から同じ予定パレットの「系列バッファ待ち生産再開」までを集計します。バッファ解放後も空パレット待ちが続く場合は、実際の生産再開まで含めます。未再開の区間は実行終了まで計上します。複数系列が同時に停止した時間は系列ごとに加算するため、合計が実行時間を超えることがあります。空パレット不足だけによる停止は、満杯発生回数・満杯停止時間・遅延PLには含めません。最大在荷も搬出・荷受けの搬送履歴から再計算します。</p></section>`;
}
export function renderAnalysis(run,data=analyzeRun(run),context={}){
  return renderCustomerResults(run,data)+renderBufferAnalysis(run)+`<details class="developer-details"><summary>開発者向け詳細</summary>${renderAnalysisMetrics(run,data)}<p class="method-note">充電待ちのうち充電停止位置の空き待ち：${minutes(data.chargePlaceWaitMs??0)}分（4台合計）。充電待ち時間に含め、別途加算しません。</p>${renderRunConditions(run,context)}</details>`;
}
export function renderComparison(runs){
  return renderCustomerComparison(runs)+`<details class="developer-details"><summary>開発者向け比較詳細</summary>${renderComparisonDetails(runs)}</details>`;
}
function renderComparisonDetails(runs) {
  const data=runs.map(analyzeRun);
  const scenario=runs[0].scenario;
  const productionDescription=scenario.productStreams?scenario.productStreams.filter(s=>s.enabled).map(s=>esc(productLabel(s))+': '+s.intervalMin+'分 / ずらし'+s.startOffsetMin+'分').join('<br>'):'系列1〜8の間隔（分）：'+scenario.lineIntervalsMin.map(n=>n===0?'停止':n).join(' / ');
  const travelDescription=scenario.motionModel==='synthetic_graph'?'区間ごとの合成距離・速度から走行時間を計算（実測ETAではありません）':`空走 ${scenario.times.emptyMin}分・積載 ${scenario.times.loadedMin}分`;
  const control=scenario.motionControl??{},phased=scenario.motionModel==='synthetic_graph'&&Object.hasOwn(control,'pickupPositioningMin');
  const phaseValue=key=>control[key]==null?'未設定':control[key]+'分';
  const handlingDescription=phased?`荷受け：姿勢移行 ${phaseValue('pickupPositioningMin')}＋挿入後 ${phaseValue('pickupForkInsertedMin')} / 荷下ろし：姿勢移行 ${phaseValue('dropoffPositioningMin')}＋挿入後 ${phaseValue('dropoffForkInsertedMin')}`:
    `荷受け ${scenario.times.pickupMin}分・荷下ろし ${scenario.times.dropoffMin}分`;
  const turnDescription=scenario.motionModel==='synthetic_graph'?`<br>停止旋回：角度÷角速度 / 角速度 ${control.turnRateDegPerSec==null?'未設定':control.turnRateDegPerSec+' deg/s'}（${control.turnRateEvidence==='synthetic-assumption'?'合成仮定':control.turnRateDegPerSec==null?'未確定':'明示条件'}）`:'';
  return `<details class="panel comparison-conditions"><summary>比較に使った共通条件 · ${scenario.durationMin}分 / ${runs[0].events.filter(e=>e.type==='PALLET_EXITED').length}PL搬出</summary><p class="method-note section">${productionDescription}<br>初期残量：${scenario.agfs.map(a=>a.id+' '+a.batteryPct+'%').join(' / ')}<br>${travelDescription}・${handlingDescription}${turnDescription}<br>手動予約 ${scenario.manualRequests?.length??0}件 / 整列機手動補充 ${scenario.alignerRefillEvents?.length??0}件${scenario.magazineUses?.length?` / 旧テスト専用マガジン使用 ${scenario.magazineUses.length}件`:""}${scenario.alignerReadyEvents?.length?` / 旧整列機準備入力 ${scenario.alignerReadyEvents.length}件`:""}<br>目的地エリアに実行可能AGFなし：${scenario.fallback==='any'?'他エリアから選定（仮定）':'待機'}</p></details><div class="comparison-grid">${runs.map((run,i)=>`<section class="panel strategy-panel"><p class="eyebrow">STRATEGY ${String(i+1).padStart(2,'0')}</p><h2>${i===0?'エリア優先あり':'エリア優先なし'}</h2><p class="muted">${i===0?'目的地エリアの実行可能AGFを優先':'全エリアの実行可能AGFから選定'}</p><div class="strategy-kpis">${metric('完了タスク',data[i].completed,'件','','success')}${metric('入庫完了',run.metrics.stored,'PL')}${metric('平均稼働率',data[i].utilizationPct.toFixed(1),'%','','accent')}${metric('保留タスク',data[i].held,'件','','warning')}</div>${utilBars(data[i])}${kindTable(data[i])}</section>`).join('')}</div>
    <section class="panel"><div class="panel-heading"><h2>同一条件の比較</h2><span class="badge sample">${runs[0].scenario.durationMin}分 / 合成入力</span></div><div class="table-scroll"><table><thead><tr><th>指標</th><th>エリア優先あり</th><th>エリア優先なし</th><th>差（あり − なし）</th></tr></thead><tbody>${[
      ['要求数（件）',...data.map(d=>d.requested)],['完了数（件）',...data.map(d=>d.completed)],['未完了数（件）',...data.map(d=>d.pending)],
      ['02発行前保留（PL）',...data.map(d=>d.preRequestHeld)],['要求待ち（分）',...data.map(d=>Number(minutes(d.requestWaitMs)))],
      ['待機時間（分）',...data.map(d=>Number(minutes(d.idleMs)))],['充電時間（分）',...data.map(d=>Number(minutes(d.chargeMs)))],
      ['交通待ち（分）',...data.map(d=>Number(minutes(d.trafficWaitMs)))],['倉庫復帰（分）',...data.map(d=>Number(minutes(d.waitReturnMs)))],['倉庫待機（分）',...data.map(d=>Number(minutes(d.hpWaitMs)))],['充電待ち（分）',...data.map(d=>Number(minutes(d.chargeWaitMs)))]
    ].map(([label,a,b])=>`<tr><td>${label}</td><td>${a}</td><td>${b}</td><td>${Number((a-b).toFixed(1))>0?'+':''}${Number((a-b).toFixed(1))}</td></tr>`).join('')}</tbody></table></div></section><p class="method-note section">比較には実行時点の設定と手動入力を複製し、共通の生産予定入力・初期条件を使用します。バッファ停止・再開による実搬出時刻と生産数は各Runの結果です。設定を変更した場合は比較実行で更新してください。差がない条件では同じ値を表示します。</p>`;
}
