import {escapeHtml as esc,stateLabel,productLabel,taskNames,clock,minutes} from './format.mjs';
import {analyzeRun,durationStatuses,durationTenths} from './replay-model.mjs';

export const metric=(label,value,unit='',sub='',tone='',icon='')=>`<div class="metric ${tone}"><div class="metric-label">${esc(label)}<span class="metric-icon" aria-hidden="true">${icon}</span></div><strong>${esc(value)}</strong><small>${esc(unit)}</small>${sub?`<span class="metric-sub">${esc(sub)}</span>`:''}</div>`;
const utilBars=data=>data.agfs.map(a=>`<div class="util-row"><span>${esc(a.id)}</span><div class="util-track"><i style="width:${a.utilizationPct}%"></i></div><b>${a.utilizationPct.toFixed(1)}%</b></div>`).join('');
const kindTable=data=>`<div class="table-scroll"><table><thead><tr><th>搬送区分</th><th>要求</th><th>完了</th><th>未完了</th></tr></thead><tbody>${data.byKind.map(k=>`<tr><td><span class="mono">${k.kind}</span> ${taskNames[k.kind]}</td><td>${k.requested}</td><td>${k.completed}</td><td>${k.pending}</td></tr>`).join('')}</tbody></table></div>`;
export function renderAnalysis(run,data=analyzeRun(run)) {
  const graph=run.scenario.motionModel==='synthetic_graph',label=s=>stateLabel(s,graph);
  const categories=durationStatuses.filter(s=>(graph||!s.startsWith('handling_'))&&(run.scenario.postTaskPolicy||!['moving_to_wait','hp_wait','waiting_hp_instruction','waiting_hp_capacity','waiting_hp_route'].includes(s)));
  return `<div class="analysis-metrics">${metric('搬送要求数',data.requested,'件','01〜05の発行済み要求','accent','↗')}${metric('完了タスク',data.completed,'件','実行期間内の完了','success','✓')}${metric('保留タスク',data.held,'件',`未完了 ${data.pending}件 / 02発行前保留 ${data.preRequestHeld}PL`,'warning','◷')}${metric('AGF平均稼働率',data.utilizationPct.toFixed(1),'%','空走・荷受け＋積載・荷下ろし','accent','▥')}
    ${metric('待機時間',minutes(data.idleMs),'分','4台合計・倉庫待機を含む')}${metric('交通待ち',minutes(data.trafficWaitMs),'分','区間・交差点・シャッター')}${metric('充電時間',minutes(data.chargeMs),'分','4台合計・充電中')}${metric('充電待ち時間',minutes(data.chargeWaitMs),'分','4台合計・2口の空き待ち')}${run.scenario.postTaskPolicy?metric('倉庫復帰走行',minutes(data.waitReturnMs),'分','通常空走とは別集計')+metric('うち倉庫待機',minutes(data.hpWaitMs),'分','4か所の待機場所への到着後')+metric('倉庫復帰保留',minutes(data.hpBlockedMs),'分','復帰先の使用待ちなど'):''}</div>
    <section class="panel"><div class="panel-heading"><div><h2>AGF タイムライン</h2><span class="muted">保存済みスナップショットの状態継続時間 · ${run.scenario.durationMin}分間</span></div><span class="badge">全期間</span></div><div class="timeline-axis">${[0,.25,.5,.75,1].map(n=>`<span>${clock(data.durationMs*n)}</span>`).join('')}</div>
    ${data.agfs.map(a=>`<div class="timeline-row"><strong>${esc(a.id)}</strong><div class="timeline-track" role="img" aria-label="${a.id} 稼働率${a.utilizationPct.toFixed(1)}%、状態別時間は下表参照">${a.timeline.map(s=>`<span class="timeline-segment timeline-${esc(s.status)}" style="width:${(s.endMs-s.startMs)*100/data.durationMs}%" title="${esc((label(s.status))+' '+clock(s.startMs)+'–'+clock(s.endMs)+(s.taskId?' '+s.taskId:''))}"></span>`).join('')}</div></div>`).join('')}
    <div class="timeline-legend">${categories.map(s=>`<span><i class="legend-dot timeline-${s}"></i>${label(s)}</span>`).join('')}</div></section>
    <div class="analysis-grid"><section class="panel"><div class="panel-heading"><h2>搬送別実績</h2><span class="muted">件</span></div>${kindTable(data)}</section><section class="panel"><div class="panel-heading"><h2>AGF別 稼働率</h2><span class="muted">全期間に対する作業時間</span></div>${utilBars(data)}<p class="method-note">稼働率＝空走＋積載走行＋荷受け＋荷下ろし。交通待ち・充電・充電移動・倉庫復帰・荷下ろし待ちは含めません。固定時間モデルでは走行と荷役を合算します。</p></section></div>
    ${data.storage?`<section class="panel section"><div class="panel-heading"><h2>倉庫容量と入庫実績</h2><span class="badge">理論最大 ${data.storage.theoretical} PL</span></div><div class="analysis-metrics">${metric('使用中',data.storage.occupied,'PL')+metric('予約済み',data.storage.reserved,'PL')+metric('端数による上段不可',data.storage.blockedUpper,'位置')+metric('今すぐ下段条件を満たす空き',data.storage.immediatelyPlaceable,'位置')+metric('追加可能上限',data.storage.additionalIfFull,'PL','今後すべて満載の仮定')+metric('追加可能数',data.storage.additionalIfPartial,'PL','今後すべて端数の仮定')}</div><p class="method-note">割当済み行・現在の在庫／予約／許可による構造上の数です。空き下段の将来の満載／端数で上段の可否が変わります。予約だけの下段は配置済みとは扱いません。行占有・経路・許可の判定は各タスクで別途行います。</p><div class="table-scroll"><table><thead><tr><th>系列／銘柄／積載状態</th><th>対象PL</th><th>入庫</th><th>未入庫</th></tr></thead><tbody>${data.products.map(p=>`<tr><td>${esc(productLabel(p))}</td><td>${p.requested}</td><td>${p.stored}</td><td>${p.pending}</td></tr>`).join('')}</tbody></table></div></section>`:''}
    <section class="panel"><div class="panel-heading"><h2>AGF別 時間内訳</h2><span class="muted">単位：分 / 各行の合計は実行時間（端数調整）</span></div><div class="table-scroll"><table><thead><tr><th>AGF</th>${categories.map(s=>`<th>${label(s)}</th>`).join('')}</tr></thead><tbody>${data.agfs.map(a=>`<tr><td>${a.id}</td>${categories.map(s=>`<td title="${a.durations[s]??0} ms">${(durationTenths(a.durations)[s]/10).toFixed(1)}</td>`).join('')}</tr>`).join('')}</tbody></table></div></section>
    <p class="method-note section">集計根拠：実行開始から終了まで、同時刻イベントは順序適用後の状態を使用。末尾イベント後の継続時間も含みます。内訳表は0.1分単位で合計が一致するよう最大剰余法で端数を配分します。稼働率は丸め前のミリ秒値で算出します。合成グラフの交通待ちはイベント状態から集計します。実CAD距離・確定ETA・現場性能ではありません。</p>`;
}
export function renderComparison(runs) {
  const data=runs.map(analyzeRun);
  const scenario=runs[0].scenario;
  const productionDescription=scenario.productStreams?scenario.productStreams.filter(s=>s.enabled).map(s=>esc(productLabel(s))+': '+s.intervalMin+'分 / ずらし'+s.startOffsetMin+'分').join('<br>'):'系列1〜8の間隔（分）：'+scenario.lineIntervalsMin.map(n=>n===0?'停止':n).join(' / ');
  const travelDescription=scenario.motionModel==='synthetic_graph'?'区間ごとの合成距離・速度から走行時間を計算（実測ETAではありません）':`空走 ${scenario.times.emptyMin}分・積載 ${scenario.times.loadedMin}分`;
  return `<details class="panel comparison-conditions"><summary>比較に使った共通条件 · ${scenario.durationMin}分 / ${runs[0].events.filter(e=>e.type==='PALLET_EXITED').length}PL搬出</summary><p class="method-note section">${productionDescription}<br>初期残量：${scenario.agfs.map(a=>a.id+' '+a.batteryPct+'%').join(' / ')}<br>${travelDescription}・荷受け ${scenario.times.pickupMin}分・荷下ろし ${scenario.times.dropoffMin}分<br>手動予約 ${scenario.manualRequests.length}件 / マガジン使用 ${scenario.magazineUses.length}件 / 整列機準備 ${scenario.alignerReadyEvents.length}件<br>目的地エリアに実行可能AGFなし：${scenario.fallback==='any'?'他エリアから選定（仮定）':'待機'}</p></details><div class="comparison-grid">${runs.map((run,i)=>`<section class="panel strategy-panel"><p class="eyebrow">STRATEGY ${String(i+1).padStart(2,'0')}</p><h2>${i===0?'エリア優先あり':'エリア優先なし'}</h2><p class="muted">${i===0?'目的地エリアの実行可能AGFを優先':'全エリアの実行可能AGFから選定'}</p><div class="strategy-kpis">${metric('完了タスク',data[i].completed,'件','','success')}${metric('入庫完了',run.metrics.stored,'PL')}${metric('平均稼働率',data[i].utilizationPct.toFixed(1),'%','','accent')}${metric('保留タスク',data[i].held,'件','','warning')}</div>${utilBars(data[i])}${kindTable(data[i])}</section>`).join('')}</div>
    <section class="panel"><div class="panel-heading"><h2>同一条件の比較</h2><span class="badge sample">${runs[0].scenario.durationMin}分 / 合成入力</span></div><div class="table-scroll"><table><thead><tr><th>指標</th><th>エリア優先あり</th><th>エリア優先なし</th><th>差（あり − なし）</th></tr></thead><tbody>${[
      ['要求数（件）',...data.map(d=>d.requested)],['完了数（件）',...data.map(d=>d.completed)],['未完了数（件）',...data.map(d=>d.pending)],
      ['02発行前保留（PL）',...data.map(d=>d.preRequestHeld)],['要求待ち（分）',...data.map(d=>Number(minutes(d.requestWaitMs)))],
      ['待機時間（分）',...data.map(d=>Number(minutes(d.idleMs)))],['充電時間（分）',...data.map(d=>Number(minutes(d.chargeMs)))],
      ['交通待ち（分）',...data.map(d=>Number(minutes(d.trafficWaitMs)))],['倉庫復帰（分）',...data.map(d=>Number(minutes(d.waitReturnMs)))],['倉庫待機（分）',...data.map(d=>Number(minutes(d.hpWaitMs)))],['充電待ち（分）',...data.map(d=>Number(minutes(d.chargeWaitMs)))]
    ].map(([label,a,b])=>`<tr><td>${label}</td><td>${a}</td><td>${b}</td><td>${Number((a-b).toFixed(1))>0?'+':''}${Number((a-b).toFixed(1))}</td></tr>`).join('')}</tbody></table></div></section><p class="method-note section">比較には実行時点の設定と手動入力を複製して使用。搬出時刻・系列・パレットIDは共通です。設定を変更した場合は比較実行で更新してください。差がない条件では同じ値を表示します。</p>`;
}
